var searchData=
[
  ['i2c_0',['I2C',['../explorer_app.html#explorer_app_i2c',1,'']]],
  ['iapd_1',['IAPD',['../structargus__results__aux__t.html#a96e4ec831460fa95438a0d07627a3bc6',1,'argus_results_aux_t']]],
  ['ide_2',['ide',['../can_app.html#can_app_e2Studio',1,'Build And Run the CAN App using e² Studio IDE'],['../e2studio.html',1,'e² Studio IDE'],['../mcuxpresso.html#autotoc_md7',1,'Install MCUXpresso IDE'],['../e2studio.html#autotoc_md14',1,'Install Renesas e² Studio IDE'],['../mcuxpresso.html',1,'MCUXpresso IDE']]],
  ['identification_3',['Software Information / Identification',['../explorer_app_cmd_details.html#cmd_info',1,'']]],
  ['implement_20hardware_20interfaces_4',['Implement hardware interfaces',['../porting_guide.html#pg_hw_interface',1,'']]],
  ['import_20a_20project_5',['import a project',['../mcuxpresso.html#autotoc_md9',1,'Import a Project'],['../e2studio.html#autotoc_md15',1,'Import a Project'],['../stm32cubeide.html#autotoc_md21',1,'Import a Project']]],
  ['import_20nxp_20mkl46z_20sdk_6',['Import NXP MKL46z SDK',['../mcuxpresso.html#autotoc_md8',1,'']]],
  ['improved_20measurement_20evaluate_20function_7',['Improved Measurement Evaluate Function',['../migration_guide.html#autotoc_md67',1,'']]],
  ['improved_20measurement_20ready_20callback_8',['Improved Measurement Ready Callback',['../migration_guide.html#autotoc_md66',1,'']]],
  ['in_20the_20s2pi_20layer_9',['in the s2pi layer',['../migration_guide.html#autotoc_md72',1,'Added HAL Functions in the S2PI layer'],['../migration_guide.html#autotoc_md71',1,'Changed HAL Functions in the S2PI layer']]],
  ['in_20your_20environment_10',['Create a new project in your environment',['../porting_guide.html#pg_new_project',1,'']]],
  ['information_20identification_11',['Software Information / Identification',['../explorer_app_cmd_details.html#cmd_info',1,'']]],
  ['initialization_12',['initialization',['../getting_started.html#autotoc_md3',1,'Initialization'],['../porting_guide.html#autotoc_md27',1,'S2PI Initialization']]],
  ['initialization_20yields_20device_20not_20connected_20error_20code_20101_13',['Device Initialization Yields Device Not Connected (Error Code -101)',['../faq.html#autotoc_md73',1,'']]],
  ['install_20mcuxpresso_20ide_14',['Install MCUXpresso IDE',['../mcuxpresso.html#autotoc_md7',1,'']]],
  ['install_20renesas_20e²_20studio_20ide_15',['Install Renesas e² Studio IDE',['../e2studio.html#autotoc_md14',1,'']]],
  ['install_20stm32cubeide_16',['Install STM32CubeIDE',['../stm32cubeide.html#autotoc_md20',1,'']]],
  ['install_20the_20opensda_20drivers_17',['Download and install the OpenSDA drivers',['../mcuxpresso.html#autotoc_md11',1,'']]],
  ['int_5fema32_18',['int_ema32',['../group__argus__fp.html#gaadc12d047db47c668f487874bdf10870',1,'fp_ema.h']]],
  ['int_5fmath_2eh_19',['int_math.h',['../int__math_8h.html',1,'']]],
  ['int_5fsqrt_20',['INT_SQRT',['../group__argus__misc.html#gae3d0f9e10d0232b7f9fa6d29854fcf09',1,'int_math.h']]],
  ['integrationtime_21',['IntegrationTime',['../structargus__meas__frame__t.html#ab76bd3b7bb6308b3ebada44c63ea399c',1,'argus_meas_frame_t']]],
  ['interface_22',['interface',['../group__can__intf.html',1,'CAN API interface'],['../group__argus__log.html',1,'Debug: Logging Interface'],['../explorer_app.html#explorer_app_python_example',1,'Python Example on Using the SCI Interface'],['../group__argus__s2pi.html',1,'S2PI: Serial Peripheral Interface'],['../group__sci.html',1,'SCI: Systems Communication Interface'],['../explorer_app.html#explorer_app_sci',1,'Serial Communication Interface'],['../group__argus__timer.html',1,'Timer: Hardware Timer Interface'],['../group__uart__intf.html',1,'UART API interface']]],
  ['interface_20can_23',['Communication Interface CAN',['../can_app.html#autotoc_md51',1,'']]],
  ['interface_20to_20pc_24',['interface to pc',['../e2studio.html#autotoc_md18',1,'Connect the UART interface to PC'],['../stm32cubeide.html#autotoc_md24',1,'Connect the UART interface to PC']]],
  ['interfaces_25',['Implement hardware interfaces',['../porting_guide.html#pg_hw_interface',1,'']]],
  ['interpolate_5factivepixels_26',['Interpolate_ActivePixels',['../group__argus__xtk__cli.html#ga094ac717ff04cbc41de66c61007ef733',1,'argus_xtalk_cal_cli.c']]],
  ['interrupt_20control_20layer_27',['IRQ: Global Interrupt Control Layer',['../group__argus__irq.html',1,'']]],
  ['interrupt_20layer_28',['Interrupt Layer',['../porting_guide.html#pg_irq',1,'']]],
  ['interrupt_20locking_29',['Concurrency and Interrupt Locking',['../porting_guide.html#autotoc_md37',1,'']]],
  ['interrupt_20priority_30',['interrupt priority',['../porting_guide.html#autotoc_md33',1,'DMA Interrupt Priority'],['../porting_guide.html#autotoc_md36',1,'Interrupt Priority']]],
  ['interrupt_20timer_20pit_31',['Periodic Interrupt Timer (PIT)',['../porting_guide.html#autotoc_md35',1,'']]],
  ['interrupts_20and_20callback_20function_32',['DMA Interrupts and Callback Function',['../porting_guide.html#autotoc_md32',1,'']]],
  ['introduction_33',['introduction',['../explorer_app.html#explorer_app_sci_intro',1,'Introduction'],['../index.html',1,'Introduction'],['../porting_guide.html#pg_introduction',1,'Introduction'],['../can_app.html#autotoc_md52',1,'Introduction']]],
  ['introduction_20of_20distinct_20global_20range_20offsets_20for_20low_20and_20high_20power_20stages_34',['Introduction of distinct global range offsets for low and high power stages',['../migration_guide.html#autotoc_md63',1,'']]],
  ['invalid_20command_35',['Invalid Command',['../explorer_app_cmd_details.html#cmd_invalid',1,'']]],
  ['invoked_36',['The Measurement Finished Callback is Never Invoked',['../faq.html#autotoc_md78',1,'']]],
  ['irq_3a_20global_20interrupt_20control_20layer_37',['IRQ: Global Interrupt Control Layer',['../group__argus__irq.html',1,'']]],
  ['irq_5flock_38',['IRQ_LOCK',['../group__argus__irq.html#ga7eb2f9c9e40114afd7d079ace7c152e7',1,'argus_irq.h']]],
  ['irq_5funlock_39',['IRQ_UNLOCK',['../group__argus__irq.html#ga41f0d51315c5971183de8750606eab22',1,'argus_irq.h']]],
  ['is_20never_20invoked_40',['The Measurement Finished Callback is Never Invoked',['../faq.html#autotoc_md78',1,'']]],
  ['is_5fbit_5fu32_41',['IS_BIT_U32',['../group__explorer__app.html#ga1078c2bfb40efe4bcfc9b4713ff01ea2',1,'explorer_macro.h']]],
  ['is_5fcan_5ftx_5fbusy_42',['is_can_tx_busy',['../group__can__intf.html#gab7d3538ccc990f117272fe473901f1a4',1,'can_api.c']]],
  ['ispowoftwo_43',['ispowoftwo',['../group__argus__misc.html#ga3109e689b3d340b1441280c3dbb53bfb',1,'int_math.h']]]
];
