var searchData=
[
  ['s2pi_3a_20serial_20peripheral_20interface_0',['S2PI: Serial Peripheral Interface',['../group__argus__s2pi.html',1,'']]],
  ['s50_20api_1',['AFBR-S50 API',['../group__argus__api.html',1,'']]],
  ['s50_20api_20examples_2',['AFBR-S50 API Examples',['../group__example__apps.html',1,'']]],
  ['s50_20explorer_20application_3',['AFBR-S50 Explorer Application',['../group__explorer__main.html',1,'']]],
  ['s50_20explorer_20application_20config_4',['AFBR-S50 Explorer Application - Config',['../group__explorer__config.html',1,'']]],
  ['s50_20explorer_20application_20tasks_5',['AFBR-S50 Explorer Application - Tasks',['../group__explorer__tasks.html',1,'']]],
  ['s50_20explorer_20application_20util_20functions_6',['AFBR-S50 Explorer Application - Util functions',['../group__core__utils.html',1,'']]],
  ['s50_20explorer_20demo_20application_7',['Data Types for the AFBR-S50 Explorer Demo Application',['../group__explorer__types.html',1,'']]],
  ['s50_20explorer_20explorer_20calibration_20functions_8',['AFBR-S50 Explorer - Explorer calibration functions',['../group__core__calib.html',1,'']]],
  ['s50_20explorer_20explorer_20configuration_20functions_9',['AFBR-S50 Explorer - Explorer configuration functions',['../group__core__cfg.html',1,'']]],
  ['s50_20explorer_20explorer_20device_20functions_10',['AFBR-S50 Explorer - Explorer Device functions',['../group__core__device.html',1,'']]],
  ['s50_20explorer_20flash_20module_11',['AFBR-S50 Explorer Flash Module',['../group__core__flash.html',1,'']]],
  ['s50_20sci_20api_12',['AFBR-S50 SCI API',['../group__explorer__api.html',1,'']]],
  ['s50_20sdk_13',['AFBR-S50 SDK',['../group__argus.html',1,'']]],
  ['scheduler_14',['Task Scheduler',['../group__scheduler.html',1,'']]],
  ['sci_20api_15',['AFBR-S50 SCI API',['../group__explorer__api.html',1,'']]],
  ['sci_3a_20byte_20stuffing_16',['SCI: Byte Stuffing',['../group__sci__bytestuffing.html',1,'']]],
  ['sci_3a_20crc8_17',['SCI: CRC8',['../group__sci__crc.html',1,'']]],
  ['sci_3a_20data_20frames_18',['SCI: Data Frames',['../group__sci__frame.html',1,'']]],
  ['sci_3a_20data_20link_20layer_19',['SCI: Data Link Layer',['../group__sci__datalink.html',1,'']]],
  ['sci_3a_20generic_20command_20definitions_20',['SCI: Generic Command Definitions',['../group__sci__cmd.html',1,'']]],
  ['sci_3a_20handshaking_21',['SCI: Handshaking',['../group__sci__handshaking.html',1,'']]],
  ['sci_3a_20systems_20communication_20interface_22',['SCI: Systems Communication Interface',['../group__sci.html',1,'']]],
  ['sdk_23',['AFBR-S50 SDK',['../group__argus.html',1,'']]],
  ['self_20test_24',['HAL Self Test',['../group__argus__test.html',1,'']]],
  ['serial_20peripheral_20interface_25',['S2PI: Serial Peripheral Interface',['../group__argus__s2pi.html',1,'']]],
  ['shot_20noise_20monitor_26',['Shot Noise Monitor',['../group__argus__snm.html',1,'']]],
  ['status_20codes_27',['status codes',['../group__argus__status.html',1,'Status Codes'],['../group__scheduler__status.html',1,'Status Codes']]],
  ['stuffing_28',['SCI: Byte Stuffing',['../group__sci__bytestuffing.html',1,'']]],
  ['systems_20communication_20interface_29',['SCI: Systems Communication Interface',['../group__sci.html',1,'']]]
];
